# Generated by Django 5.2.4 on 2025-07-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_alter_topping_pizza_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_name',
            field=models.CharField(choices=[('supreme', 'Supreme'), ('veggie', 'Veggie'), ('meat_lovers', 'Meat Lovers'), ('hawaiian', 'Hawaiian'), ('cheese', 'Cheese')], default='cheese', max_length=200),
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=models.CharField(choices=[('pepperoni', 'Pepperoni'), ('sausage', 'Sausage'), ('hamburger', 'Hamburger'), ('spinach', 'Spinach'), ('olives', 'Olives'), ('pineapple', 'Pineapple'), ('canadian_bacon', 'Canadian Bacon'), ('cheese_blend', '3 Cheese Blend'), ('onion', 'Onion'), ('bacon', 'Bacon')], default='cheese_blend', max_length=200),
        ),
    ]
