# Generated by Django 5.2.4 on 2025-07-11 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_alter_pizza_pizza_name_alter_topping_topping_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'comments'},
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_image',
            field=models.ImageField(blank=True, help_text='Upload an image of this pizza', null=True, upload_to='pizza_images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pizzas.pizza'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pizzas.pizza'),
        ),
    ]
